// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package bugs

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed code.svg
var codeIconData []byte
var codeIcon = &fyne.StaticResource{
	StaticName:    "code.svg",
	StaticContent: codeIconData,
}

//go:embed bug.svg
var bugIconData []byte
var bugIcon = &fyne.StaticResource{
	StaticName:    "bug.svg",
	StaticContent: bugIconData,
}

//go:embed flag.svg
var flagIconData []byte
var flagIcon = &fyne.StaticResource{
	StaticName:    "flag.svg",
	StaticContent: flagIconData,
}
